### ISSUE TITLE
Endless loop while running

### ISSUE THREAD

**Issue by celguar** [ML-Dev-Hub/csv_trans#14]
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Translating DataFrame:   0%|                                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 125, in _main
  File "multiprocessing\spawn.py", line 236, in prepare
  File "multiprocessing\spawn.py", line 287, in _fixup_main_from_path
  File "runpy.py", line 268, in run_path
  File "runpy.py", line 97, in _run_module_code
  File "runpy.py", line 87, in _run_code
  File "E:\Games\MANGOS\soft\csv_translate\retro_proxy\csv_translate.py", line 4, in <module>
Translating DataFrame:   0%|                                                                     | 0/1 [00:00<?, ?it/s]    translate("../input/classic_details_sp.csv", "en", "sp", sep=';')
  File "E:\Games\MANGOS\soft\csv_translate\retro_python\lib\site-packages\csv_trans\translate.py", line 41, in translate
    data = translate_dataframe(data, source_lang, target_lang)
  File "E:\Games\MANGOS\soft\csv_translate\retro_python\lib\site-packages\csv_trans\utils.py", line 170, in translate_dataframe
    with Pool(num_threads) as pool:
  File "multiprocessing\context.py", line 119, in Pool
  File "multiprocessing\pool.py", line 212, in __init__
  File "multiprocessing\pool.py", line 303, in _repopulate_pool
  File "multiprocessing\pool.py", line 326, in _repopulate_pool_static
  File "multiprocessing\process.py", line 121, in start
  File "multiprocessing\context.py", line 327, in _Popen
Translating DataFrame:   0%|                                                                     | 0/1 [00:00<?, ?it/s]
  File "multiprocessing\popen_spawn_win32.py", line 45, in __init__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "multiprocessing\spawn.py", line 154, in get_preparation_data
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 134, in _check_not_importing_main
  File "multiprocessing\spawn.py", line 125, in _main

**Comment by saeedahmadicp** [comment]
@celguar, thank you for bringing this issue to our attention. We are currently working on fixing it and will release a new version once the code is updated.

**Comment by saeedahmadicp** [comment]
Fixed in v2.0.0 — the v2 engine removed the process-pool path that caused the Windows multiprocessing spawn loop. Please reopen if it recurs on 2.0.1.
