### ISSUE TITLE
Error running on command line

### ISSUE THREAD

**Issue by colindj1120** [ML-Dev-Hub/csv_trans#15]
OS: Win 11

Error: 

C:\Users\CS2 KANZI PC>csv_trans -f "C:/USERS/CS2 KANZI PC/Downloads/test/Result.csv" -fs "," -sl "ja" -tl "en"
Translating DataFrame:   0%|                                                                     | 0/1 [00:00<?, ?it/s]Exception in thread Thread-4 (_handle_results):
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python312\Lib\multiprocessing\pool.py", line 579, in _handle_results
    task = get()

  File "C:\Program Files\Python312\Lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())

TypeError: NotValidPayload.__init__() missing 1 required positional argument: 'val'

**Comment by saeedahmadicp** [comment]
Fixed in v2.0.0 — provider exceptions no longer cross process boundaries or fail to deserialize. Please reopen if you still hit this on 2.0.1
